name: Update ToolHive Reference Docs

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'ToolHive version to update reference docs for'
        required: true
        default: 'latest'
  repository_dispatch:
    types: [published-release]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: update-toolhive-reference
  cancel-in-progress: false

jobs:
  update-reference:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"


      - name: Determine version
        id: get-version
        run: |
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Echo timestamp
        run: |
          echo "Current time: $(date -u)" > timestamp.txt
          echo "Version: ${{ steps.get-version.outputs.version }}" >> timestamp.txt

      - name: Check for changes
        id: git-diff
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.git-diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          branch: update-toolhive-reference-${{ steps.get-version.outputs.version }}
          title: |
            Update ToolHive reference docs for ${{ steps.get-version.outputs.version }}
          body: |
            This PR updates the ToolHive CLI and API reference documentation for release: ${{ steps.get-version.outputs.version }}.
          commit-message: |
            Update ToolHive reference docs for ${{ steps.get-version.outputs.version }}
          labels: |
            autogen-docs
          delete-branch: true
          sign-commits: true
